{% set version = "0.2.8" %}

package:
  name: dataspyre
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/D/DataSpyre/DataSpyre-{{ version }}.tar.gz
  sha256: 09d84b25c77d5fd7662df50c51822d93ad0d2e98590bfa80b6747f6a31e82f34

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cherrypy
    - jinja2
    - matplotlib-base
    - numpy
    - pandas
    - six >=1.11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - spyre

about:
  home: https://github.com/adamhajari/spyre
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Web Application Framework for simple user interface.'

extra:
  recipe-maintainers:
    - ocefpaf
