{% set version = "0.3.0" %}

package:
  name: dataspyre
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/D/DataSpyre/dataspyre-{{ version }}.tar.gz
  sha256: bd4a065493c3e4c238753391bdf252e917151a0e0d0c77be980b2a1f9ff77963

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - cherrypy
    - jinja2
    - matplotlib-base
    - numpy
    - pandas
    - six >=1.11.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - spyre

about:
  home: https://github.com/adamhajari/spyre
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Web Application Framework for simple user interface.'

extra:
  recipe-maintainers:
    - ocefpaf
