{% set version = "0.2.7" %}

package:
  name: dataspyre
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/D/DataSpyre/DataSpyre-{{ version }}.tar.gz
  sha256: 170a95c735715365581a21ac58e4631aba5fa9af60a72ed56012798e0fed4022

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
  run:
    - python
    - cherrypy
    - jinja2
    - matplotlib
    - numpy
    - pandas
    - six >=1.11.0

test:
  imports:
    - spyre

about:
  home: https://github.com/adamhajari/spyre
  license: MIT
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Web Application Framework for simple user interface.'

extra:
  recipe-maintainers:
    - ocefpaf
