travis:
  secure:
    BINSTAR_TOKEN: k/ZyI8k5TP3CvfM4MRd6A73kM6IayFB1DNK9b5vRCDODdoC1oE3piVVHhv2Om1jb/6A24Mq8zkQboRk8gJhZDInmyNKswCxAY+ragHuUbMmFUYQTCPi4ua5A+stl/OSbsVkGjrAuA/pi2vTlXVvxuvpXqy7VaHX/9t79eGwazj2nw7fp7mo2U5t6IRwX3QwZ/ZRbh+dr7uuX1eWNJPYFGpzWpDw7FZE6IeWYsyiVi/4hL5GUVeqq+qHPRbOvVbZ6BHQFLT3PhbZW+ODdPs7A1Y+MJ6JT4n+HBHJYuzcgooKiYud/P0I0gzBndYtbyoo1Bhaf6v4qMxGohe/dhsUoXjZ6VSgp3qR7ocg5IVczk74mK1PDLUu0xzrWTGiLMT8e/0/YCxNCIBSiUiwczxdcauFleE/77LLVQPDym+8C1kPXp4XokBDOw0I6/rsqYkYk2dH2GMfToDiiB5F2AZLejw9bH0xhW3hQt/0uHMUHK3XscLxvT94AhXzR6GWyA1l4WMHXlqVMscPRQ0ysVT7uDUjwCafUr+6d5hRn8gmbonlcItuj9gejhxtvaObU0KDfKMbWRwgvsW/yFWnImE+JYEFQJOH4j6HwNOvtFiZtSIH6k0rt5mONXwBqgtbS7+7lOOriNxrc9Z6haiQO/gPf81ZUCLJmQ5Q9N3F6qbW8N2U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
