travis:
  secure:
    BINSTAR_TOKEN: amyOw8sHV0jQaKgrAPFdYX+jcJB9zT1Urc0o/1b3yJsi3CEVeY1kH+YTA/okwZ1qhuxEDxv3ypxj2D83DlXrK8YksHXA94Z4TwhCtd6mjEr0z3/xu9CrNbwjBcr7j2Hz/ifFwPL633qRlE4JPIXfoYglmD0C/HM3V0Hjs7Gvegmo95REbg2Bjz17y7C+OBqPTrtVo6XHNTR1SPzm/Aj0SFR5HhkmLHy+OPatXXFudmEsGp1//hSYIIHubht2Q0ySycoEmJ/xfCDNJ/c0llC0aE+ZiDvFL6k7xRbBq0I2nSfXGIGGoZI7sf3mIELHDdhK5rpRss+AtzmtRKuFnwy+dPQxk27YECx6xDfRXwt2MYZZKzz24WRu628c0fgoPG3ZK8WZ5ftgL3arVn3hAIVhEVgG3JTE3kmXPJxhhcEfaJndvT9AuBd7hz7nZYV8qqP36BjktbMfv73DcMuu0vDuLRl0qJ3z2Bxd9+Rkdwcmm391u5koIcYnWSDSsFNok2yLPKtXhYucM+0+IIJHE0qV8doBxzTMwXbiH8qZ4K3Z224L5RcxLLML7RGZIjZGFmC4+hv52v7Gh00APHzrWBpO3Gw+YVD4ESZiEyRR6zONdKoQb16ogZJmGNPIQh/O95kAy13emrskcHWkQGiu2qaYGzX52PV5w+w5VKv0ThDg97g=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
